[project]
name = "extractor"
version = "2.0.0"
description = "This a tool to help a teacher track his students progress in codecademy.com."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.6",
    "dynaconf>=3.2.7",
    "psycopg2-binary>=2.9.10",
]
